config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'dashboard/dashboard'

  resources :drivers
  resources :facilities
  resources :patients
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  match '/signup', to: 'static_pages#sign_up', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def home
    if user_signed_in?
      @user = current_user
      if @user[:meta_type] == 'Patient'
        redirect_to patient_path(@user.meta.id)
      elsif @user[:meta_type] == 'Driver'
        redirect_to driver_path(@user.meta.id)
      end
    end
  end

  def map
    @coords_array = Facility.get_facility_coords
  end


  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h2>A Production of the ARC</h2>

<ul>

</ul>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="text-center jumbotron">
  <h1>Welcome to Drivalysis</h1>
  <h3></h3>
  <br/>
</div>

app/views/static_pages/locate.html.erb
<% provide(:title, 'Locate') %>
<div id=maprim>
<%= render 'layouts/map' %>
</div>

app/views/static_pages/map.html.erb
<% provide(:title, 'Map') %>
<div id=maprim>
<%= render 'layouts/map' %>
</div>

app/views/static_pages/sign_up.html.erb
<div class="page-header">
  <h1 class="text-center">I am a ..</h1>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-2">
 <%= link_to "Patient", new_patient_path, class: 'btn btn-primary'%>
  </div>
  <div class="col-md-4 col-md-offset-2">
  <%= link_to "Driver",  new_driver_path, class: 'btn btn-primary'%>
  </div>
</div>