config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'dashboard/dashboard'

  resources :drivers
  resources :facilities
  resources :patients
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  match '/signup', to: 'static_pages#sign_up', via: 'get'

end

app/models/facility.rb
class Facility < ActiveRecord::Base

    def self.get_facility_coords
    facilities = Facility.all

    facility_coords_array = []

    facilities.each do |facility|
      facility_coords_array << {"lat" => facility.latitude, "lng" => facility.longitude, "name" => facility.name, "what" => facility.address}
    end

      facility_coords_array

    end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :address, :county, :city, :zip_code, :beds, :telephone, :type)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for(@facility, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @facility.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h4>

      <ul>
      <% @facility.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :county, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :county, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip_code, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :beds, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :beds, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telephone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telephone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :type, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<div class="page-header">
  <%= link_to facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @facility, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing facility</h1>
</div>

<%= render 'form' %>

app/views/facilities/index.html.erb
<div class="page-header">
  <%= link_to new_facility_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Facility
  <% end %>
  <h1>Listing facilities</h1>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Address</th>
            <th>County</th>
            <th>City</th>
            <th>Zip code</th>
            <th>Beds</th>
            <th>Telephone</th>
            <th>Type</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @facilities) do |facility| %>
            <td><%= facility.name %></td>
            <td><%= facility.address %></td>
            <td><%= facility.county %></td>
            <td><%= facility.city %></td>
            <td><%= facility.zip_code %></td>
            <td><%= facility.beds %></td>
            <td><%= facility.telephone %></td>
            <td><%= facility.facility_type %></td>
            <td><%= link_to 'Show', facility %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/facilities/new.html.erb
<div class="page-header">
  <%= link_to facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New facility</h1>
</div>

<%= render 'form' %>

app/views/facilities/show.html.erb
<div class="page-header">
  <%= link_to facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_facility_path(@facility), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show facility</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @facility.name %></dd>

  <dt>Address:</dt>
  <dd><%= @facility.address %></dd>

  <dt>County:</dt>
  <dd><%= @facility.county %></dd>

  <dt>City:</dt>
  <dd><%= @facility.city %></dd>

  <dt>Zip code:</dt>
  <dd><%= @facility.zip_code %></dd>

  <dt>Beds:</dt>
  <dd><%= @facility.beds %></dd>

  <dt>Telephone:</dt>
  <dd><%= @facility.telephone %></dd>

  <dt>Type:</dt>
  <dd><%= @facility.type %></dd>

</dl>