config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'dashboard/dashboard'

  resources :drivers
  resources :facilities
  resources :patients
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  match '/signup', to: 'static_pages#sign_up', via: 'get'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  validates :name,  presence: true
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/}, presence: true
  validates :address, presence: true, :length => { :maximum => 2000 }
  validates :neighborhood, presence: true
  validates :wheel_chair_accessible, presence: true
  validates :willing_to_carpool, presence: true
  validates :assistance_comfort_level, presence: true

  has_one :user, as: :meta, dependent: :destroy
  accepts_nested_attributes_for :user
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
   before_action :authenticate_user!, :except => [:new, :create]
   before_action :set_driver, only: [:destroy]
   #before_filter :validate_user, :except => [:new, :create]

  def validate_user
    redirect_to '/signup' unless current_user.meta_id.to_s == params[:id].to_s or current_user.admin == true
  end
  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    @driver = Driver.find(params[:id])

  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
    @driver = Driver.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)
    @user = {}
    respond_to do |format|
      if @driver.save
        @user = User.find_by_email(driver_params[:user_attributes][:email])
        sign_in(@user)
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :phone, :available_monday, :available_tueday, :neighborhood, :address,:available_wednesday, :available_thursday, :available_friday, :available_saturday, :available_sunday,:available_time_monday, :available_time_tuesday, :available_time_wednesday, :available_time_thursday,:available_time_friday, :available_time_sauterday, :available_time_sunday, :wheel_chair_accessible, :willing_to_carpool, :assistance_comfort_level, user_attributes: [:id, :email, :password ])
     #params.require(:driver).permit!
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
  
end

app/views/drivers/_form.html.erb
<%= form_for(@driver, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @driver.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h4>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user_attributes do |u| %>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= u.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= u.text_field :password, class: "form-control" %>
    </div>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :neighborhood, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :neighborhood, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :available_monday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_monday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :available_time_monday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :available_time_monday, {:ampm => true} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :available_tuesday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_tuesday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :available_time_tuesday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :available_time_tuesday, {:ampm => true, :default => false} %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :available_wednesday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_wednesday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :available_time_wednesday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :available_time_wednesday, {:ampm => true} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :available_thursday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_thursday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :avialable_time_thurday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :available_time_thursday, {:ampm => true} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :available_friday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_friday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :available_time_friday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :available_time_friday, {:ampm => true} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :available_saturday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_saturday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :available_time_sauterday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :available_time_sauterday, {:ampm => true} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :available_sunday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :available_sunday, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :avilable_time_sunday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.time_select :avilable_time_sunday, {:ampm => true} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :wheel_chair_accessible, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :wheel_chair_accessible, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :willing_to_carpool, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :willing_to_carpool, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :assistance_comfort_level, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
       <%= f.select :assistance_comfort_level, [[1,1],[2,2],[3,3], [4,4],[5,5]] %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<div class="page-header">
  <%= link_to drivers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @driver, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing driver</h1>
</div>

<%= render 'form' %>

app/views/drivers/index.html.erb
<div class="page-header">
  <%= link_to new_driver_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Driver
  <% end %>
  <h1>Listing drivers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Available time</th>
            <th>Available days</th>
            <th>Wheel chair accessible</th>
            <th>Willing to carpool</th>
            <th>Assistance comfort level</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @drivers) do |driver| %>
            <td><%= driver.name %></td>
            <td><%= driver.user.email %></td>
            <td><%= driver.phone %></td>
            <td><%= driver.available_time %></td>
            <td><%= driver.available_days %></td>
            <td><%= driver.wheel_chair_accessible %></td>
            <td><%= driver.willing_to_carpool %></td>
            <td><%= driver.assistance_comfort_level %></td>
            <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/drivers/new.html.erb
<div class="page-header">
  <%= link_to drivers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New driver</h1>
</div>

<%= render 'form' %>

app/views/drivers/show.html.erb
<div class="page-header">
  <%= link_to drivers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_driver_path(@driver), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1 class="text-center">Show driver</h1>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <dl class="dl-horizontal">
      <dt>Name:</dt>
      <dd><%= @driver.name %></dd>

      <dt>Email:</dt>
      <dd><%= @driver.user.email %></dd>

      <dt>Phone:</dt>
      <dd><%= @driver.phone %></dd>

      <dt>Address:</dt>
      <dd><%= @driver.address %></dd>

      <dt>Neighborhood :</dt>
      <dd><%= @driver.neighborhood %></dd>

      <dt>Available Monday:</dt>
      <dd><%= @driver.available_monday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_monday.strftime("%I:%M%p") %></dd>

      <dt>Available Tueday:</dt>
      <dd><%= @driver.available_tuesday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_tuesday.strftime("%I:%M%p") %></dd>

      <dt>Available Wednesday:</dt>
      <dd><%= @driver.available_wednesday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_wednesday.strftime("%I:%M%p") %></dd>

      <dt>Available Thursday:</dt>
      <dd><%= @driver.available_thursday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_thursday.strftime("%I:%M%p") %></dd>

      <dt>Available Friday:</dt>
      <dd><%= @driver.available_friday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_friday.strftime("%I:%M%p") %></dd>

      <dt>Available Saturday:</dt>
      <dd><%= @driver.available_saturday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_sauterday.strftime("%I:%M%p") %></dd>

      <dt>Available Sunday:</dt>
      <dd><%= @driver.available_sunday ? 'yes' : 'no' %></dd>

      <dt>Available time:</dt>
      <dd><%= @driver.available_time_sunday.strftime("%I:%M%p") %></dd>

      <dt>Wheel chair accessible:</dt>
      <dd><%= @driver.wheel_chair_accessible  ? 'yes' : 'no' %></dd>

      <dt>Willing to carpool:</dt>
      <dd><%= @driver.willing_to_carpool ? 'yes' : 'no' %></dd>

      <dt>Assistance comfort level:</dt>
      <dd><%= @driver.assistance_comfort_level %></dd>

    </dl>
  </div>
</div>