config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'dashboard/dashboard'

  resources :drivers
  resources :facilities
  resources :patients
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  match '/signup', to: 'static_pages#sign_up', via: 'get'

end

app/views/layouts/_map.html.erb
<div id="map" style='height: 500px; '></div>
<script type="text/javascript">


function initMap() {
  var pos;
 var map = new google.maps.Map(document.getElementById('map'), {
    center: pos,
    zoom: 12,
     styles: [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"color":"#ffffff"}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"color":"#000000"},{"lightness":13}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#144b53"},{"lightness":14},{"weight":1.4}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#08304b"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#0c4152"},{"lightness":5}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#0b434f"},{"lightness":25}]},{"featureType":"road.arterial","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"road.arterial","elementType":"geometry.stroke","stylers":[{"color":"#0b3d51"},{"lightness":16}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"}]},{"featureType":"transit","elementType":"all","stylers":[{"color":"#146474"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#021019"}]}]


  });

 var coords = <%= @coords_array.to_json.html_safe %>
 console.log(coords);

 for (var i = 0; i < coords.length; i++) {
        var data = coords[i];
        var myLatlng = new google.maps.LatLng(data.lat, data.lng);
        var icon_color = 'https://maps.google.com/mapfiles/ms/icons/green-dot.png';

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: data.name,
            icon: icon_color
        });
      }

 // Try HTML5 geolocation.
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        pos = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        map.setCenter(pos);
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
  }
  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
                          'Error: The Geolocation service failed.' :
                          'Error: Your browser doesn\'t support geolocation.');

}

    </script>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?v=3.22&key=AIzaSyDOINxdZoRY9KAdxlZhMEiWjLcdwofGqys&callback=initMap">
    </script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', '/about' %></li>
<li><%= link_to 'Map', '/map' %></li>
<% if user_signed_in? %>
<% if current_user.admin? %>
<li><%= link_to 'Facilities', facilities_path %></li>
<li><%= link_to 'Patients', patients_path %></li>
<li><%= link_to 'Drivers', drivers_path %></li>
<% end %>
<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
<% if current_user.meta_type == "Driver" %>
<% driver = Driver.find(current_user.meta_id) %>
<li><%= link_to 'Settings', edit_driver_path(driver) %></li>
<% end %>
<% if current_user.meta_type == "Patient" %>
 <% patient = Patient.find(current_user.meta_id) %>
<li><%= link_to 'Settings', edit_patient_path(patient) %></li>
<% end %>
<% else %>
  <li><%= link_to 'Sign Up!', '/signup' %></li>
  <li><%= link_to('Login', new_user_session_path)  %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= full_title(yield(:title)) %></title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container-fluid">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
<body>
</html>